
- name: Create /etc/kubernetes/config directory
  become: yes
  file:
    path: /etc/kubernetes/config
    state: directory

- name: Download the official Kubernetes release binaries
  shell: |
    wget -q --show-progress --https-only --timestamping \
      "https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kube-apiserver" \
      "https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kube-controller-manager" \
      "https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kube-scheduler" \
      "https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl"

- name: Add execution permissions
  file:
    path: "{{ item }}"
    state: file
    mode: a+x
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubectl

- name: Install the Kubernetes binaries
  become: yes
  shell: |
    mv "{{ item }}" /usr/local/bin/
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubectl
