
- name: Download and Install the etcd binaries
  import_tasks: install-etcd.yml

- name: Create directories and move certs
  import_tasks: setup-dir.yml

- name: Create the etcd service
  import_tasks: etcd-service.yml
