- name: Generate kube-proxy-csr.json file
  template:
    src: kube-proxy-csr.json.j2
    dest: /tmp/k8s/kube-proxy-csr.json

- name: Generate proxy cert and key
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      kube-proxy-csr.json | cfssljson -bare kube-proxy
  args:
    chdir: /tmp/k8s/
