
- name: Retrieve the Pod CIDR range for the current compute instance
  shell: |
   curl -s -H "Metadata-Flavor: Google" \
    http://metadata.google.internal/computeMetadata/v1/instance/attributes/pod-cidr
  register: pod_cidr

- name: Create the bridge network configuration file
  become: yes
  template:
    src: 10-bridge.conf.j2
    dest: /etc/cni/net.d/10-bridge.conf

- name: Create the loopback network configuration file
  become: yes
  template:
    src: 99-loopback.conf.j2
    dest: /etc/cni/net.d/99-loopback.conf
