
- name: Create the containerd configuration directory
  become: yes
  file:
    path: /etc/containerd/
    state: directory

- name: Create the containerd configuration file
  become: yes
  template:
    src: containerd.config.toml.j2
    dest: /etc/containerd/config.toml

- name: Create the containerd.service systemd unit file
  become: yes
  template:
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service
