
- name: Move keys and configs
  become: yes
  shell: |
    mv "{{ item.src }}" "{{ item.dest }}"
  loop:
    - {src: "{{ inventory_hostname }}-key.pem", dest: "/var/lib/kubelet/{{ inventory_hostname }}-key.pem"}
    - {src: "{{ inventory_hostname }}.pem", dest: "/var/lib/kubelet/{{ inventory_hostname }}.pem"}
    - {src: "{{ inventory_hostname }}.kubeconfig", dest: "/var/lib/kubelet/kubeconfig"}
    - {src: 'ca.pem', dest: '/var/lib/kubernetes/ca.pem'}

- name: Retrieve the Pod CIDR range for the current compute instance
  shell: |
   curl -s -H "Metadata-Flavor: Google" \
    http://metadata.google.internal/computeMetadata/v1/instance/attributes/pod-cidr
  register: pod_cidr
  
- name: Create the kubelet-config.yaml configuration file
  become: yes
  template:
    src: kubelet-config.yaml.j2
    dest: /var/lib/kubelet/kubelet-config.yaml

- name: Create the kubelet.service systemd unit file
  become: yes
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
