
- name: Install dependencies
  become: yes
  package:
   name: "{{ item }}"
  with_items:
   - socat
   - conntrack
   - ipset

- name: Disable swap
  become: yes
  shell: |
    swapoff -a

- name: Disable swap in fstab
  become: yes
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'

- name: Download binaries
  shell: |
    wget -q --show-progress --https-only --timestamping \
      https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.21.0/crictl-v1.21.0-linux-amd64.tar.gz \
      https://github.com/opencontainers/runc/releases/download/v1.0.0-rc93/runc.amd64 \
      https://github.com/containernetworking/plugins/releases/download/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz \
      https://github.com/containerd/containerd/releases/download/v1.4.4/containerd-1.4.4-linux-amd64.tar.gz \
      https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl \
      https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kube-proxy \
      https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubelet

- name: Create installation directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/cni/net.d
    - /opt/cni/bin
    - /var/lib/kubelet
    - /var/lib/kube-proxy
    - /var/lib/kubernetes
    - /var/run/kubernetes

- name: Install worker binaries
  become: yes
  shell: |
    mkdir containerd
    tar -xvf crictl-v1.21.0-linux-amd64.tar.gz
    tar -xvf containerd-1.4.4-linux-amd64.tar.gz -C containerd
    tar -xvf cni-plugins-linux-amd64-v0.9.1.tgz -C /opt/cni/bin/
    mv runc.amd64 runc
    chmod +x crictl kubectl kube-proxy kubelet runc
    mv crictl kubectl kube-proxy kubelet runc /usr/local/bin/
    mv containerd/bin/* /bin/
