
- name: Start and Enable the services
  become: yes
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - containerd
    - kubelet
    - kube-proxy
