
- name: Install the etcd server and the etcdctl command line utility
  shell: |
    cat <<EOF | tee -a /etc/hosts
    10.250.0.20 worker-0
    10.250.0.21 worker-1
    10.20.0.22 worker-2
    EOF
  when: inventory_hostname in groups['controllers']
  tags:
    - do
